version: '3.8'

services:
  app:
    build: .
    container_name: phone-commerce-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DBHOST=postgres
      - DBPORT=5432
      - DBUSER=postgres
      - DBPASSWORD=postgres
      - DBNAME=ecommerce_db
      - DB_POOL_MIN=0
      - DB_POOL_MAX=10
      - DB_POOL_IDLE_TIMEOUT=30000
      - DBSSL=false
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: phone-commerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: phone-commerce-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
    driver: bridge 